### ISSUE TITLE
jaeger query es failed

### ISSUE THREAD

**Issue by jojotong** [kubegems/kubegems#413]
![image](https://user-images.githubusercontent.com/100849526/215252574-f58fd966-39bc-4ede-9045-8fa2dc23c881.png)
related issues: https://github.com/jaegertracing/jaeger/issues/2976

**Comment by jojotong** [comment]
Resolved by shutdown all jaeger collectors, delete the bad indexes, then restart the collectors.
So old trace data will lost.

**Comment by ailoyu** [comment]
Hi @jojotong ,

Can we fix that without deleting indices? Because it's okay if the tracing data is on dev environment, but what if the tracing data is on Production? Do we have any way to fix without deleting the indices of ElasticSearch?

I actually did it on dev Environment and it solved this error, but cannot do that in Production, just asking haha, 

The current way I am using:

`
kubectl scale deploy jaeger-collector --replicas=0
`

`
curl -X DELETE http://<elasticsearch>:9200/jaeger-*
`

`kubectl scale deploy jaeger-collector --replicas=3`



Feel free if you have any ideals or solution to share.

Thanks a lot!!!
